{{ config(
    materialized="incremental",
    on_schema_change="append_new_columns",
    unique_key="id",
    alias="sf_account_t",
    tags=["salesforce"]
) }}

{%- set unique_key = config.get('unique_key') -%}
{%- set incr_key = 'lastmodifieddate' -%}
{%- set column_list = 'id,
    borrower_user_id__c,
    clcommon__legal_entity_type__c,
    lead_uen__c,
    name,
    billing_address_text__c,
    postal_code__c,
    acc_name__c,
    creditlimitdate__c,
    nric__c,
    rm_mail_id__c,
    referred_by__c,
    type__c,
    clcommon__active__c,
    customer_type__c,
    dda_approved__c,
    daily_utilization__c,
    genesis_status__c,
    investor_daily_utilization__c,
    investor_name_userid__c,
    investor_type__c,
    investor_user_id__c,
    last_loan_disbursal_date__c,
    loan__broker__c,
    peer__auto_invest__c,
    peer__borrower_exposure_limit_amount__c,
    peer__funds_available_for_investment__c,
    peer__funds_in_queue__c,
    peer__funds_not_in_queue__c,
    peer__investor_status__c,
    peer__isactiveborrower__c,
    peer__isactiveinvestor__c,
    peer__portfolio_amount__c,
    peer__sign_agreement__c,
    peer__status__c,
    peer__total_remaining_investment__c,
    peer__verified__c,
    peer__credit_rating_matrix__c,
    peer__date_of_birth__c,
    peer__first_name__c,
    peer__gender__c,
    peer__last_name__c,
    peer__national_id__c,
    total_amount_deposited_new__c,
    total_insurance_clawback_including_gst__c,
    total_loan_amount__c,
    total_of_premium_paid_till_date__c,
    total_validus_commission__c,
    total_withdrawal__c,
    type,
    user_id__c,
    withdrawal_amount_requested__c,
    withdrawal_cleared__c,
    write_off_amount__c,
    accountnumber,
    annualrevenue,
    industry,
    numberofemployees,
    ownership,
    rating,
    website,
    billingpostalcode,
    loan__active__c,
    shippingpostalcode,
    cvf_utilization__c,
    ispersonaccount,
    is_buyer__c,
    kfels_limit__c,
    kfels_utilization__c,
    ksl_limit__c,
    ksl_utilization__c,
    limit_ard__c,
    limit_ar_non_disclosed__c,
    limit_cvf__c,
    limit_po__c,
    limit_wc__c,
    max_limit__c,
    max_utilization__c,
    non_cvf_limit__c,
    non_cvf_utilization__c,
    smm_limit__c,
    smm_utilization__c,
    smrt_limit__c,
    smrt_utilization__c,
    st_limit__c,
    st_utilization__c,
    utilization_ar_disclosed__c,
    utilization_ar_non_disclosed__c,
    utilization_purchase_order__c,
    utilization_working_capital__c,
    sales_team_lead__c,
    lastmodifieddate' -%}

{% set src_table = "source." ~ config.get("alias")[:-2] %}
{% set src_data = config.get("alias").split("_")[0] %}
{{ gen_sql(unique_key, incr_key, column_list, src_data, src_table) | trim }}
