{{ config(
    materialized="incremental",
    on_schema_change="append_new_columns",
    unique_key="id",
    alias="sf_application_t",
    tags=["salesforce"]
) }}

{%- set unique_key = config.get('unique_key') -%}
{%- set incr_key = 'lastmodifieddate' -%}
{%- set column_list = 'id,
    postman_id__c,
    genesis__cl_product_name__c,
    wc_subcategory_list__c,
    application_date__c,
    genesis__status__c,
    loan_status__c,
    creditapprovalstatus__c,
    sub_stage__c,
    genesis__parent_application__c,
    genesis__maturity_date__c,
    account_customer_type__c,
    borrower_account_name__c,
    createddate,
    genesis__account__c,
    genesis__gross_annual_income__c,
    genesis__is_over_21__c,
    is1tmcustomer__c,
    is_it_card_based__c,
    is_it_citi_based__c,
    postal_code__c,
    request_period__c,
    sales_rm_email_id__c,
    service_rate__c,
    total_invoice_amount__c,
    uen__c,
    uen_number__c,
    user_id__c,
    user_type__c,
    application_approved_date__c,
    application_fees__c,
    application_verified_date__c,
    application_verified_month__c,
    borrower_id__c,
    borrower_name__c,
    credit_rating_matrix_id__c,
    credit_rating_matrix_name__c,
    debtor_name__c,
    disclosure__c,
    investor_type__c,
    invoice_amount__c,
    invoice_number__c,
    loan_id__c,
    sector__c,
    risk_rating__c,
    timebased_mp_date__c,
    timebased_mp_status__c,
    timebased_mp_time__c,
    genesis__apr__c,
    genesis__action__c,
    genesis__amortization_term__c,
    genesis__cl_purpose__c,
    genesis__credit_limit__c,
    genesis__credit_rating__c,
    genesis_loan_app__c,
    is_rejected__c,
    is_approved__c,
    buyer_account__c,
    buyer_type__c,
    buyer_uen__c,
    bounced_cheques__c,
    cbs_poor_rating__c,
    cbs_risk_grade__c,
    credit_risk__c,
    credit_underwritter_id__c,
    current_ratio__c,
    dpd_30__c,
    dsr__c,
    is_l2_approver__c,
    increase_limit_application__c,
    industry_type__c,
    industry__c,
    insurance_premium__c,
    invoice_approval_status__c,
    is_renewal__c,
    limit_unutilised__c,
    pd__c,
    pg_age_65__c,
    profit_margin__c,
    pending_credit_suits__c,
    pending_suits_amount__c,
    recommended_cvf_customer_limit__c,
    recommended_customer_limit__c,
    recommended_limit__c,
    recommended_non_cvf_customer_limit__c,
    recommended_pricing__c,
    recommended_tenor__c,
    rejection_reason__c,
    requested_interest__c,
    requested_limit_amount__c,
    requested_limit__c,
    requested_to_increase_limit__c,
    ssic_code__c,
    winding_up_bankruptcy_suits__c,
    yob__c,
    source__c,
    genesis__requested_loan_amount__c,
    lastmodifieddate,
    rejection_date__c' -%}

{% set src_table = "source." ~ config.get("alias")[:-2] %}
{% set src_data = config.get("alias").split("_")[0] %}
{{ gen_sql(unique_key, incr_key, column_list, src_data, src_table) | trim }}
