{{ config(
    materialized="incremental",
    on_schema_change="append_new_columns",
    unique_key="id",
    alias="sf_investment_order_t",
    tags=["salesforce"]
) }}

{%- set unique_key = config.get('unique_key') -%}
{%- set incr_key = 'lastmodifieddate' -%}
{%- set column_list = 'borrower_name__c,
    cl_contract_date__c,
    contract_date__c,
    contract_status__c,
    date_of_repayment__c,
    days_past_due__c,
    delayed_amount__c,
    disbursed_date__c,
    due_date__c,
    estimated_interest__c,
    fees_amount_paid_after_commission__c,
    fees_paid_excl_waived__c,
    gst_on_insurance_premium_paid__c,
    gst_on_validus_commission_from_interest__c,
    gst_on_insurance_premium_clawback__c,
    gst_on_validus_commission_of_an_interest__c,
    id,
    insurance_premium_clawback__c,
    insurance_premium_paid__c,
    insured__c,
    interest_remaining__c,
    investor_id__c,
    investor_name__c,
    investor_type__c,
    interest_rate_p_a__c,
    interest_rate_p_m__c,
    lcv_date__c,
    is_it_principal_fully_paid__c,
    is_it_insured__c,
    loan_app_id__c,
    loan__account__c,
    loan__archived__c,
    loan__buying_price__c,
    loan__certificate_rate__c,
    loan__charged_off_fees__c,
    loan__charged_off_interest__c,
    loan__charged_off_principal__c,
    loan__income_reinvested__c,
    loan__interest_amount_paid__c,
    loan__interest_balance__c,
    loan__interest_disbursed_to_investor__c,
    loan__inv_accrued_interest_amt__c,
    loan__investment_amount__c,
    loan__investor_end_date__c,
    loan__investor_loan_id__c,
    loan__investor_start_date__c,
    loan__late_fees_amount_paid__c,
    loan__loan_principal_remaining__c,
    loan__loan_start_date__c,
    loan__loan_status__c,
    loan__loan__c,
    loan__principal_amount_paid__c,
    loan__principal_disbursed_to_investor__c,
    loan__principal_reinvested__c,
    loan__rebate_amount_paid__c,
    loan__reinvest_interest__c,
    loan__reinvest_principal__c,
    loan__reinvest_service_charge__c,
    loan__remaining_investment_amount__c,
    loan__service_charge_on_full_payment_amount__c,
    loan__service_fee_on_total_payment__c,
    loan__service_rate__c,
    loan__total_amount_paid__c,
    loan__write_off_amount__c,
    maturity_date__c,
    net_interest_rate__c,
    net_returns__c,
    outstanding_amount__c,
    peer__investment_booking__c,
    principal_paid__c,
    percent_investment_amount__c,
    user_id__c,
    validus_invested_amount__c,
    customer_type__c,
    fees_remaining__c,
    interest_waived__c,
    total_balance__c,
    createddate,
    lastmodifieddate,
    estimated_interest_with_validus_commissi__c,
    estimated_interest_without_commission__c' -%}

{% set src_table = "source." ~ config.get("alias")[:-2] %}
{% set src_data = config.get("alias").split("_")[0] %}
{{ gen_sql(unique_key, incr_key, column_list, src_data, src_table) | trim }}
