/*==============*/
/* g_datateam */

CREATE GROUP g_datateam;

-- GRANT
-- Database Permision ALL ( CREATE | TEMPORARY | TEMP)
    GRANT ALL PRIVILEGES ON DATABASE data_lake TO GROUP g_datateam;

-- Schema Permision ALL ( CREATE | USAGE )
    GRANT ALL PRIVILEGES ON SCHEMA conformed     TO GROUP g_datateam;
    GRANT ALL PRIVILEGES ON SCHEMA enriched      TO GROUP g_datateam;
    GRANT ALL PRIVILEGES ON SCHEMA source        TO GROUP g_datateam;
    GRANT ALL PRIVILEGES ON SCHEMA standardized  TO GROUP g_datateam;
    GRANT ALL PRIVILEGES ON SCHEMA staging       TO GROUP g_datateam;
    GRANT ALL PRIVILEGES ON SCHEMA metadata      TO GROUP g_datateam;


-- Table Permision ALL ( SELECT | INSERT | UPDATE | DELETE | REFERENCES)
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA conformed      TO GROUP g_datateam;
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA enriched       TO GROUP g_datateam;
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA source         TO GROUP g_datateam;
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA standardized   TO GROUP g_datateam;
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA staging        TO GROUP g_datateam;
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA metadata       TO GROUP g_datateam;

-- FUNCTION Permision ALL (EXECUTE)
    GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA conformed       TO GROUP g_datateam;
    GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA enriched        TO GROUP g_datateam;
    GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA source          TO GROUP g_datateam;
    GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA standardized    TO GROUP g_datateam;
    GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA staging         TO GROUP g_datateam;
    GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA metadata        TO GROUP g_datateam;

-- PROCEDURE Permision ALL (EXECUTE)
    GRANT ALL PRIVILEGES ON ALL PROCEDURES IN SCHEMA conformed       TO GROUP g_datateam;
    GRANT ALL PRIVILEGES ON ALL PROCEDURES IN SCHEMA enriched        TO GROUP g_datateam;
    GRANT ALL PRIVILEGES ON ALL PROCEDURES IN SCHEMA source          TO GROUP g_datateam;
    GRANT ALL PRIVILEGES ON ALL PROCEDURES IN SCHEMA standardized    TO GROUP g_datateam;
    GRANT ALL PRIVILEGES ON ALL PROCEDURES IN SCHEMA staging         TO GROUP g_datateam;
    GRANT ALL PRIVILEGES ON ALL PROCEDURES IN SCHEMA metadata        TO GROUP g_datateam;

-- Default Permission
    -- Tables
    ALTER DEFAULT PRIVILEGES IN SCHEMA conformed        GRANT ALL PRIVILEGES ON TABLES TO GROUP g_datateam;
    ALTER DEFAULT PRIVILEGES IN SCHEMA enriched         GRANT ALL PRIVILEGES ON TABLES TO GROUP g_datateam;
    ALTER DEFAULT PRIVILEGES IN SCHEMA source           GRANT ALL PRIVILEGES ON TABLES TO GROUP g_datateam;
    ALTER DEFAULT PRIVILEGES IN SCHEMA standardized     GRANT ALL PRIVILEGES ON TABLES TO GROUP g_datateam;
    ALTER DEFAULT PRIVILEGES IN SCHEMA staging          GRANT ALL PRIVILEGES ON TABLES TO GROUP g_datateam;
    ALTER DEFAULT PRIVILEGES IN SCHEMA metadata         GRANT ALL PRIVILEGES ON TABLES TO GROUP g_datateam;

    -- Functions
    ALTER DEFAULT PRIVILEGES IN SCHEMA conformed        GRANT ALL PRIVILEGES ON FUNCTIONS TO GROUP g_datateam;
    ALTER DEFAULT PRIVILEGES IN SCHEMA enriched         GRANT ALL PRIVILEGES ON FUNCTIONS TO GROUP g_datateam;
    ALTER DEFAULT PRIVILEGES IN SCHEMA source           GRANT ALL PRIVILEGES ON FUNCTIONS TO GROUP g_datateam;
    ALTER DEFAULT PRIVILEGES IN SCHEMA standardized     GRANT ALL PRIVILEGES ON FUNCTIONS TO GROUP g_datateam;
    ALTER DEFAULT PRIVILEGES IN SCHEMA staging          GRANT ALL PRIVILEGES ON FUNCTIONS TO GROUP g_datateam;
    ALTER DEFAULT PRIVILEGES IN SCHEMA metadata         GRANT ALL PRIVILEGES ON FUNCTIONS TO GROUP g_datateam;

    -- PROCEDURES 
    ALTER DEFAULT PRIVILEGES IN SCHEMA conformed        GRANT ALL PRIVILEGES ON PROCEDURES TO GROUP g_datateam;
    ALTER DEFAULT PRIVILEGES IN SCHEMA enriched         GRANT ALL PRIVILEGES ON PROCEDURES TO GROUP g_datateam;
    ALTER DEFAULT PRIVILEGES IN SCHEMA source           GRANT ALL PRIVILEGES ON PROCEDURES TO GROUP g_datateam;
    ALTER DEFAULT PRIVILEGES IN SCHEMA standardized     GRANT ALL PRIVILEGES ON PROCEDURES TO GROUP g_datateam;
    ALTER DEFAULT PRIVILEGES IN SCHEMA staging          GRANT ALL PRIVILEGES ON PROCEDURES TO GROUP g_datateam;
    ALTER DEFAULT PRIVILEGES IN SCHEMA metadata         GRANT ALL PRIVILEGES ON PROCEDURES TO GROUP g_datateam;

    -- Allow member of this group to access objects created by data_worker
    ALTER DEFAULT PRIVILEGES FOR USER data_worker GRANT ALL PRIVILEGES ON TABLES TO GROUP g_datateam;

-- GRANT SYSTEM VIEW
    GRANT SYSTEM VIEW
    GRANT USAGE                 ON SCHEMA pg_catalog  TO GROUP g_datateam;
    GRANT SELECT  ON ALL TABLES IN SCHEMA pg_catalog  TO GROUP g_datateam;


/*==============*/
/* g_etl_worker */
-- Create
CREATE GROUP g_etl_worker;

-- Grant access to schema
    GRANT USAGE ON SCHEMA source TO GROUP g_etl_worker;
    GRANT USAGE ON SCHEMA standardized TO GROUP g_etl_worker;
    GRANT USAGE ON SCHEMA conformed TO GROUP g_etl_worker;
    GRANT USAGE ON SCHEMA enriched TO GROUP g_etl_worker;
    GRANT USAGE ON SCHEMA staging to GROUP g_etl_worker;
    GRANT USAGE ON SCHEMA metadata to GROUP g_etl_worker;

-- Grant DML
    GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA source TO GROUP g_etl_worker;
    GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA standardized TO GROUP g_etl_worker;
    GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA conformed TO GROUP g_etl_worker;
    GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA enriched TO GROUP g_etl_worker;
    GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA staging TO GROUP g_etl_worker;
    GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA metadata TO GROUP g_etl_worker;

-- Permission to create object
    GRANT CREATE ON SCHEMA standardized TO GROUP g_etl_worker;
    GRANT CREATE ON SCHEMA conformed TO GROUP g_etl_worker;
    GRANT CREATE ON SCHEMA enriched TO GROUP g_etl_worker;
    GRANT CREATE ON SCHEMA staging TO GROUP g_etl_worker;
    GRANT CREATE ON SCHEMA metadata TO GROUP g_etl_worker;

-- Default privileges for future objects
    ALTER DEFAULT PRIVILEGES IN SCHEMA source GRANT SELECT,INSERT,UPDATE,DELETE ON TABLES TO GROUP g_etl_worker;
    ALTER DEFAULT PRIVILEGES IN SCHEMA standardized GRANT SELECT,INSERT,UPDATE,DELETE ON TABLES TO GROUP g_etl_worker;
    ALTER DEFAULT PRIVILEGES IN SCHEMA conformed GRANT SELECT,INSERT,UPDATE,DELETE ON TABLES TO GROUP g_etl_worker;
    ALTER DEFAULT PRIVILEGES IN SCHEMA enriched GRANT SELECT,INSERT,UPDATE,DELETE ON TABLES TO GROUP g_etl_worker;
    ALTER DEFAULT PRIVILEGES IN SCHEMA staging GRANT SELECT,INSERT,UPDATE,DELETE ON TABLES TO GROUP g_etl_worker;
    ALTER DEFAULT PRIVILEGES IN SCHEMA metadata GRANT SELECT,INSERT,UPDATE,DELETE ON TABLES TO GROUP g_etl_worker;

/*==============*/
/* g_bi_readall */
-- Create
    CREATE GROUP g_bi_readall;

-- Grant access to schema
    GRANT USAGE ON SCHEMA conformed TO GROUP g_bi_readall;
    GRANT USAGE ON SCHEMA enriched TO GROUP g_bi_readall;
    GRANT USAGE ON SCHEMA metadata to GROUP g_bi_readall;

-- Grant SELECT
    GRANT SELECT ON ALL TABLES IN SCHEMA conformed TO GROUP g_bi_readall;
    GRANT SELECT ON ALL TABLES IN SCHEMA enriched TO GROUP g_bi_readall;
    GRANT SELECT ON ALL TABLES IN SCHEMA metadata TO GROUP g_bi_readall;    

-- Default privileges for future objects
    ALTER DEFAULT PRIVILEGES IN SCHEMA conformed GRANT SELECT ON TABLES TO GROUP g_bi_readall;
    ALTER DEFAULT PRIVILEGES IN SCHEMA enriched GRANT SELECT ON TABLES TO GROUP g_bi_readall;
    ALTER DEFAULT PRIVILEGES IN SCHEMA metadata GRANT SELECT ON TABLES TO GROUP g_bi_readall;

-- Allow member of this group to access objects created by data_worker
    ALTER DEFAULT PRIVILEGES FOR USER data_worker GRANT SELECT ON TABLES TO GROUP g_bi_readall;
